apiVersion: apps/v1
kind: Deployment
metadata:
  name: default
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - name: http
          protocol: TCP
          containerPort: 80
